# Data Wrangling of the CDP Cities Water Risk Data 2021, 2018, 2017

## Load the libraries and datasets

In [186]:
##load libraries
import pandas as pd

In [187]:
#read the .csv file 
df_2021 = pd.read_csv('2021_Cities_Water_Security_Risks.csv')
df_2018 = pd.read_csv('2018_-_Cities_Water_Risks.csv')
df_2017 = pd.read_csv('2017_Cities_Water_Risks.csv')


#For finding state codes
state_df = pd.read_csv('State code.csv')

In [188]:
#let's have a look at each dataframe 
df_2021.head(5)

,Questionnaire Name,Account Number,Account Name,Country,CDP Region,ParentSection,Section,Question Number,Question Name,Row Number,Water security risk drivers,Anticipated timescale,Estimated magnitude of potential impact,Estimated probability of impact,Risk description
0,Cities 2021,1093,"City of Atlanta, GA",United States of America,North America,14. Water Security,Water Supply,14.2a,Please identify the risks to your city’s water...,1,Increased water stress,Short-term (by 2025),Serious,NaN,The city depends on one river for water supply...
1,Cities 2021,1093,"City of Atlanta, GA",United States of America,North America,14. Water Security,Water Supply,14.2a,Please identify the risks to your city’s water...,2,Higher water prices,Current,Serious,NaN,The water cost burden is felt across all ZIP c...
2,Cities 2021,1184,"City of Austin, TX",United States of America,North America,14. Water Security,Water Supply,14.2a,Please identify the risks to your city’s water...,1,Increased water stress,Short-term (by 2025),Extremely serious,High,Central Texas is drought prone and we depend o...
3,Cities 2021,1499,Ajuntament de Barcelona,Spain,Europe,14. Water Security,Water Supply,14.2a,Please identify the risks to your city’s water...,1,Increased water stress,Current,Serious,Medium-high,The downscaling of the climate projections at ...
4,Cities 2021,1499,Ajuntament de Barcelona,Spain,Europe,14. Water Security,Water Supply,14.2a,Please identify the risks to your city’s water...,2,Declining water quality,Medium-term (by 2050),Less Serious,Medium,A reduction in water resources availability c...

In [189]:
df_2018.head(5)

,Account No,Organisation,City,Country,Region,Access,C40,Reporting year,Risks to city's water supply,Timescale,Magnitude,Risk description,Current population,Population year,City Location
0,1093,City of Atlanta,Atlanta,United States of America,North America,public,NaN,2018,Increased water stress or scarcity,Short-term,Serious,The city depends on one river for water supply...,450182.0,2017,"(33.749, -84.388)"
1,1093,City of Atlanta,Atlanta,United States of America,North America,public,NaN,2018,Higher water prices,Current,Serious,The water cost burden is felt across all ZIP c...,450182.0,2017,"(33.749, -84.388)"
2,1184,City of Austin,Austin,United States of America,North America,public,C40,2018,Increased water stress or scarcity,Medium-term,Extremely serious,NaN,1265974.0,2017,"(30.2672, -97.7431)"
3,1499,Ajuntament de Barcelona,Barcelona,Spain,Europe,public,C40,2018,Increased water stress or scarcity,Current,Extremely serious,The downscaling of the climate projections at ...,1604555.0,2015,"(41.3823, 2.1775)"
4,1499,Ajuntament de Barcelona,Barcelona,Spain,Europe,public,C40,2018,Declining water quality,Medium-term,Serious,A reduction in water resources availability c...,1604555.0,2015,"(41.3823, 2.1775)"

In [190]:
df_2017.head(5)

,Account No,Organisation,City,Country,Region,Access,C40,Reporting year,Risks to city’s water supply,​Timescale,Magnitude,Risk description,Current population,Population year,City location,Country location
0,54100,"City of Columbia, MO","Columbia, MO",USA,North America,Public,NaN,2017,Flooding,NaN,NaN,NaN,119098,2017,"(38.951705, -92.334072)","(37.09024, -95.712891)"
1,55799,"City of Arlington, VA","Arlington, VA",USA,North America,Public,NaN,2017,Higher water prices,NaN,NaN,NaN,220400,2016,"(37.226486, -76.002594)","(37.09024, -95.712891)"
2,35870,City of Miami,Miami,USA,North America,Public,NaN,2017,Increased water stress or scarcity,Current,Extremely serious,NaN,413892,2014,"(25.7617, -80.1918)","(37.09024, -95.712891)"
3,36043,Abuja Federal Capital Territory,Abuja,Nigeria,Africa,Public,NaN,2017,Higher water prices,Short-term,Serious,NaN,2440000,2017,"(9.076479, 7.398574)","(9.081999, 8.675277)"
4,36039,Accra Metropolitan Assembly,Accra,Ghana,Africa,Public,C40,2017,Flooding,NaN,NaN,NaN,2291352,2013,"(5.565437, -0.168191)","(7.946527, -1.023194)"

### Were the cities in the 2021, 2018 and 2017 dataframes asked the same question?

For comparison purposes, we want to make sure that the cities were asked the same questions across the years 2021, 2018, 2017. 

Let's start by checking what the 2021 dataset is about.

In [191]:
#Check what the 2021 question were about 
print("Cities in the 2021 dataset were asked about {}, specifically question {} asked to {}.".format(df_2021["Section"].unique(), 
                                                                                                     df_2021["Question Number"].unique(), 
                                                                                                     df_2021["Question Name"].unique()))

Cities in the 2021 dataset were asked about ['Water Supply'], specifically question ['14.2a'] asked to ['Please identify the risks to your city’s water security as well as the timescale and level of risk.'].

Because we have no information on the question asked in the 2018 and 2017 dataset on water security, we will fetch this information from the full data set.

In [192]:
#Because we have no information on the question asked in the 2018 and 2017 survey, we will fetch this information from the full data set 
#load the dataset from the full questionnaire 
fulldf_2018 = pd.read_csv('2018_Full_Cities_Dataset.csv')
fulldf_2017 = pd.read_csv('2017_Full_Cities_Dataset.csv')

In [193]:
#load the dataset from the 2018 full questionnaire 
fulldf_2018 = pd.read_csv('2018_Full_Cities_Dataset.csv')

#only select the rows for water supply
waterdf_2018 = fulldf_2018[fulldf_2018['Section'].str.contains("Water Supply")]

In [194]:
#we have multiple questions related water supply 
#but the one that looks like our 2018 water risk dataset is question 15.3a 
waterdf_2018.head(5)

,Questionnaire,Year Reported to CDP,Account Number,Organization,Country,CDP Region,Parent Section,Section,Question Number,Question Name,Column Number,Column Name,Row Number,Row Name,Response Answer,Comments,File Name,Last update
32,CDP Cities 2018,2018,54529,City of Leicester,United Kingdom of Great Britain and Northern I...,Europe,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,1,Risks,1,NaN,Increased water stress or scarcity,NaN,NaN,24/06/2020 05:28:18 AM
42,CDP Cities 2018,2018,54631,Prefeitura de Cajamar,Brazil,Latin America,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,2,Timescale,1,NaN,Short-term,NaN,NaN,24/06/2020 05:28:18 AM
73,CDP Cities 2018,2018,54298,Dalian Municipal People's Government,China,East Asia,Water,Water Supply Management,15.4,Please select the actions you are taking to re...,1,Risks,8,NaN,Higher water prices,NaN,NaN,24/06/2020 05:28:18 AM
79,CDP Cities 2018,2018,36469,Comune dell'Aquila,Italy,Europe,Water,Water Supply,15.3,Do you foresee substantive risks to your city’...,0,NaN,0,NaN,No,NaN,NaN,24/06/2020 05:28:18 AM
148,CDP Cities 2018,2018,31090,District of Columbia,United States of America,North America,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,3,Magnitude,4,NaN,Serious,NaN,NaN,24/06/2020 05:28:18 AM

In [195]:
#let's update the previous dataset to only contain question 15.3
waterdf_2018 = fulldf_2018[fulldf_2018['Question Number'].str.contains("15.3a")]
waterdf_2018

,Questionnaire,Year Reported to CDP,Account Number,Organization,Country,CDP Region,Parent Section,Section,Question Number,Question Name,Column Number,Column Name,Row Number,Row Name,Response Answer,Comments,File Name,Last update
32,CDP Cities 2018,2018,54529,City of Leicester,United Kingdom of Great Britain and Northern I...,Europe,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,1,Risks,1,NaN,Increased water stress or scarcity,NaN,NaN,24/06/2020 05:28:18 AM
42,CDP Cities 2018,2018,54631,Prefeitura de Cajamar,Brazil,Latin America,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,2,Timescale,1,NaN,Short-term,NaN,NaN,24/06/2020 05:28:18 AM
148,CDP Cities 2018,2018,31090,District of Columbia,United States of America,North America,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,3,Magnitude,4,NaN,Serious,NaN,NaN,24/06/2020 05:28:18 AM
201,CDP Cities 2018,2018,54459,City of Reykjavík,Iceland,Europe,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,3,Magnitude,3,NaN,NaN,NaN,NaN,24/06/2020 05:28:18 AM
218,CDP Cities 2018,2018,36426,Riga City,Latvia,Europe,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,3,Magnitude,1,NaN,Less Serious,NaN,NaN,24/06/2020 05:28:18 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186565,CDP Cities 2018,2018,70017,Alcaldia de Palmira,Colombia,Latin America,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,2,Timescale,2,NaN,Long-term,NaN,NaN,24/06/2020 05:28:18 AM
186568,CDP Cities 2018,2018,54109,City of Bloomington,United States of America,North America,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,2,Timescale,3,NaN,Long-term,NaN,NaN,24/06/2020 05:28:18 AM
186660,CDP Cities 2018,2018,831812,Municipalidad de Puerto Barrios,Guatemala,Latin America,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,4,Risk description,2,NaN,NaN,NaN,NaN,24/06/2020 05:28:18 AM
186672,CDP Cities 2018,2018,35874,City of Phoenix,United States of America,North America,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,4,Risk description,2,NaN,"Phoenix, because of its desert environment, ha...",NaN,NaN,24/06/2020 05:28:18 AM
186679,CDP Cities 2018,2018,58569,City of Podgorica,Montenegro,Europe,Water,Water Supply,15.3a,Please identify the risks to your city’s water...,1,Risks,2,NaN,Declining water quality,NaN,NaN,24/06/2020 05:28:18 AM

In [196]:
#print water the question about water supply in the 2018 dataset was about
print("Cities in the 2018 dataset were asked about {}, specifically question {} asked to {}.".format(waterdf_2018["Section"].unique(),
                                                                                                     waterdf_2018["Question Number"].unique(),
                                                                                                     waterdf_2018["Question Name"].unique()))

Cities in the 2018 dataset were asked about ['Water Supply'], specifically question ['15.3a'] asked to ['Please identify the risks to your city’s water supply as well as the timescale and level of risk.'].

In [197]:
#load the dataset from the 2017 full questionnaire 
fulldf_2017 = pd.read_csv('2017_Full_Cities_Dataset.csv')

#inspect the dataframe 
fulldf_2017.head(7)

#there is no information about the question asked.

,Project Name,Account Number,Account Name,Module Name,Page Name,Page Repeat,Page Repeatable,Repeat Start,Repeat End,QuestionNumber,Question UniqueReference,Response Value,Rows,Table Columns Unique Reference,External Reference,External Reference Id,Authority Name,Table Column Number
0,CDP Cities 2017,55442,Município de Moita,Community,Community - External Verification,NaN,NotRepeatable,NaN,NaN,C1.13,Cities-C1.13-ExternalVerification,No,0,NaN,NaN,NaN,NaN,0
1,CDP Cities 2017,55442,Município de Moita,Community,Community - GHG Emissions Data,NaN,NotRepeatable,NaN,NaN,C1.5,Cities-C1.5-GHGEmissionsData,NaN,2,Cities-C1.5-C3-Confidence,NaN,NaN,NaN,3
2,CDP Cities 2017,55442,Município de Moita,Community,Community - GHG Emissions Data,NaN,NotRepeatable,NaN,NaN,C1.5,Cities-C1.5-GHGEmissionsData,NaN,3,Cities-C1.5-C4-Comments,NaN,NaN,NaN,4
3,CDP Cities 2017,55442,Município de Moita,Community,Community - GHG Emissions Data,NaN,NotRepeatable,NaN,NaN,C1.5,Cities-C1.5-GHGEmissionsData,46598,4,Cities-C1.5-C2-EmissionsCO2e,NaN,NaN,NaN,2
4,CDP Cities 2017,55442,Município de Moita,Community,Community - GHG Emissions Data,NaN,NotRepeatable,NaN,NaN,C1.5,Cities-C1.5-GHGEmissionsData,49910,3,Cities-C1.5-C2-EmissionsCO2e,NaN,NaN,NaN,2
5,CDP Cities 2017,55442,Município de Moita,Community,Community - GHG Emissions Data,NaN,NotRepeatable,NaN,NaN,C1.9a,Cities-C1.9a-GHGEmissionsData,NaN,6,Cities-C1.9a-C2-EmissionsMetric,NaN,NaN,NaN,2
6,CDP Cities 2017,55442,Município de Moita,Community,Community - GHG Emissions Data,NaN,NotRepeatable,NaN,NaN,C1.9a,Cities-C1.9a-GHGEmissionsData,NaN,9,Cities-C1.9a-C2-EmissionsMetric,NaN,NaN,NaN,2

In [198]:
# According to the website where the dataset was fetched from (https://data.cdp.net/Water/2017-Cities-Water-Risks/qaye-zhaz), the cities in 2017 were asked a question about water supply
print("While we have no information about the question asked in the 2017 data set, according to the CDP website, cities in the 2017 dataset were also asked about {}.".format(waterdf_2018["Section"].unique()))

While we have no information about the question asked in the 2017 data set, according to the CDP website, cities in the 2017 dataset were also asked about ['Water Supply'].

Each city was asked a question pertaining to water supply. Specifically they were asked to identify the risks to their water security or water supply as well as the timescale and level of risk. 

Having established that the 2021, 2018 and 2017 dataframes all asked about risk to water supply, we can proceed with merging them into one big dataframe for analysis.

## Creating and cleaning the 2021, 2018, 2017 US data sets

### Matching the column names 

To merge the three datasets, we need to make sure that the column names match each other. Let's check the names of the columns of each datasets.

In [199]:
#print the columns names 
print('columns of the 2021 dataframe:{}\n'.format(list(df_2021.columns)))
print('columns of the 2018 dataframe:{}\n'.format(list(df_2018.columns)))
print('columns of the 2017 dataframe:{}\n'.format(list(df_2017.columns)))

columns of the 2021 dataframe:['Questionnaire Name', 'Account Number', 'Account Name', 'Country', 'CDP Region', 'ParentSection', 'Section', 'Question Number', 'Question Name', 'Row Number', 'Water security risk drivers', 'Anticipated timescale', 'Estimated magnitude of potential impact', 'Estimated probability of impact', 'Risk description']

columns of the 2018 dataframe:['Account No', 'Organisation', 'City', 'Country', 'Region', 'Access', 'C40', 'Reporting year', "Risks to city's water supply", 'Timescale', 'Magnitude', 'Risk description', 'Current population', 'Population year', 'City Location']

columns of the 2017 dataframe:['Account No', 'Organisation', 'City', 'Country', 'Region', 'Access', 'C40', 'Reporting year', 'Risks to city’s water supply', '\u200bTimescale', 'Magnitude', 'Risk description', 'Current population', 'Population year', 'City location', 'Country location']

There are some noticeable differences in the column names of our variable of interests (e.g., **Anticipated timescale** in the 2021 dataframe but **Timescale** and **\u200bTimescale** in the 2018, 2017 dataframe respectively). Therefore, we will make sure to match the column names of the 2018 and 2017 datasets to match those the 2021 dataset for our variables of interest, namely **Account name** (for the cities/states), **Country**, **Water security risk drivers**, **Anticipated timescale**, **Estimated magnitude of potential impact** and **Risk desription**.

In [200]:
#Renaming columns for 2017 and 2018 datasets to match the 2021 dataset only for the variable of interest. 
df_2018.rename(columns={"City": "Account Name", "Risks to city's water supply": "Water security risk drivers", "Timescale": "Anticipated timescale","Magnitude":"Estimated magnitude of potential impact"},inplace=True)
df_2017.rename(columns={"City": "Account Name", "Risks to city’s water supply": "Water security risk drivers", "\u200bTimescale": "Anticipated timescale","Magnitude":"Estimated magnitude of potential impact"},inplace=True)

#print the columns names 
print('columns of the 2021 dataframe:{}\n'.format(list(df_2021.columns)))
print('columns of the 2018 dataframe:{}\n'.format(list(df_2018.columns)))
print('columns of the 2017 dataframe:{}\n'.format(list(df_2017.columns)))

columns of the 2021 dataframe:['Questionnaire Name', 'Account Number', 'Account Name', 'Country', 'CDP Region', 'ParentSection', 'Section', 'Question Number', 'Question Name', 'Row Number', 'Water security risk drivers', 'Anticipated timescale', 'Estimated magnitude of potential impact', 'Estimated probability of impact', 'Risk description']

columns of the 2018 dataframe:['Account No', 'Organisation', 'Account Name', 'Country', 'Region', 'Access', 'C40', 'Reporting year', 'Water security risk drivers', 'Anticipated timescale', 'Estimated magnitude of potential impact', 'Risk description', 'Current population', 'Population year', 'City Location']

columns of the 2017 dataframe:['Account No', 'Organisation', 'Account Name', 'Country', 'Region', 'Access', 'C40', 'Reporting year', 'Water security risk drivers', 'Anticipated timescale', 'Estimated magnitude of potential impact', 'Risk description', 'Current population', 'Population year', 'City location', 'Country location']

Since our focus is on the United States of America, in the next section we will clean and create a new data frame with only responses from cities in the US for the 2021, 2018 and 2017 dataframe.

### Cleaning and creating three seperate US datasets

#### 2021 US dataset

In [201]:
# Let's begin by creating a dataframe labelled "usdf" with only the columns we want to retain 
usdf_21 = df_2021[['Country', 
            'Account Name',
            'Water security risk drivers', 
            'Anticipated timescale',
            'Estimated magnitude of potential impact',
            'Risk description']].copy()

#add the condition that country is USA and that water supply is a current problem 
usdf_21 = usdf_21[(usdf_21.Country == "United States of America") & (usdf_21['Anticipated timescale'] == "Current")]

#add a year variable
usdf_21["Year"] = 2021

#### 2018 US dataset

In [202]:
# Creating the 2018 cleaned up dataframe with the columns we want to retain 
usdf_18 = df_2018[['Country', 
            'Account Name',
            'Water security risk drivers', 
            'Anticipated timescale',
            'Estimated magnitude of potential impact',
            'Risk description',"City Location"]].copy()

#add the condition that country is USA and the water security risk is a current problem 
usdf_18 = usdf_18[(usdf_18.Country == "United States of America") & (usdf_18['Anticipated timescale'] == "Current")]

#add a year variable
usdf_18["Year"] = 2018

#### 2017 US dataset

In [203]:
#The same is then done for the 2017 dataset
usdf_17 = df_2017[['Country', 
            'Account Name',
            'Water security risk drivers', 
            'Anticipated timescale',
            'Estimated magnitude of potential impact',
            'Risk description',"City location"]].copy()

#add the condition that country is USA and that water supply is a current problem 
usdf_17 = usdf_17[(usdf_17.Country == "USA") & (usdf_17['Anticipated timescale'] == "Current")]

#add a year variable
usdf_17["Year"] = 2017

## Creating the states and city columns

Because our aim is to analyse state wide issues on water supply, we will create a column with the names of the states for each city.

### 2021 US dataset 

The 2021 data set has the names of the state and city in the column **Account Name**, therefore we will seperate these into two seperate columns.

In [204]:
#create the variable City and State
usdf_21[['City', 'State']] = usdf_21["Account Name"].str.split(',', expand=True)

#drop account Name
usdf_21.drop(['Account Name'], axis = 1, inplace=True)

usdf_21.head(5)

,Country,Water security risk drivers,Anticipated timescale,Estimated magnitude of potential impact,Risk description,Year,City,State
1,United States of America,Higher water prices,Current,Serious,The water cost burden is felt across all ZIP c...,2021,City of Atlanta,GA
17,United States of America,Inadequate or ageing water supply infrastructure,Current,Serious,New York City’s drinking water meets orexceeds...,2021,New York City,NY
31,United States of America,Increased water stress,Current,Extremely serious,"Lake Mead, which is 90% of Southern Nevada's s...",2021,City of Las Vegas,NV
35,United States of America,Increased water demand,Current,Serious,Water costs are higher due to infrastructure c...,2021,City of Las Vegas,NV
36,United States of America,Environmental regulations,Current,Less Serious,Water restrictions have led to more conservati...,2021,City of Las Vegas,NV

### 2018 US dataset

On the other hand, the 2018 and 2017 datasets do not have any information on the states of the cities. Additionally, since many US cities such as Atlanta exist in multiple states we cannot simply merge a city from our datasets to a state dataset found online. However, because the 2018 and 2017 datasets do include the cities' coordinates, we can use this information to find the states using the library ````GEOPY````.

In [205]:
#import geopy for finding states
from geopy.extra.rate_limiter import RateLimiter
from geopy.geocoders import Nominatim
import pandas as pd
geolocator = Nominatim(user_agent="user_agent")

# add rate limit to send 1 request per second
reverse = RateLimiter(geolocator.reverse, min_delay_seconds=1)

In [206]:
# The same is then done for the 2018 dataset
usdf_18 = df_2018[['Country', 
            'Account Name',
            'Water security risk drivers', 
            'Anticipated timescale',
            'Estimated magnitude of potential impact',
            'Risk description',"City Location"]].copy()


#add the condition that country is USA and the water security risk is a current problem 
usdf_18 = usdf_18[(usdf_18.Country == "United States of America") & (usdf_18['Anticipated timescale'] == "Current")]
usdf_18["Year"] = 2018

In [207]:
#Creating a coordinateds tuple for creating the state variable using the city location feature

#clean the coorndinates string
usdf_18['City Location'] = usdf_18['City Location'].str.replace(r'[()]',"")
usdf_18['City Location'] = usdf_18['City Location'].str.replace('_', '', regex=False)
usdf_18[['lat','lng']]=usdf_18["City Location"].str.split(',',expand=True)



#creating a coordinate tuple
usdf_18['coordinates'] = usdf_18[['lat', 'lng']].apply(tuple, axis=1)

/var/folders/nj/bh632zpj6rvfbwpg7f8ff4jr0000gn/T/ipykernel_58660/1600104917.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  usdf_18['City Location'] = usdf_18['City Location'].str.replace(r'[()]',"")

In [208]:
state_list = [] # Initialize empty list

# get location coordinates
geo_locv  = usdf_18.coordinates.values

#manually add Hawaii coordinates because the api doesn't recognize the ones given by dataset
geo_locv[16] = (21.304547,-157.855676)

for cord in geo_locv:
    # send request
    location = reverse(cord, addressdetails=True)
    # get state value
    state = location.raw["address"].get("state")
    # store state value
    state_list.append(state)
# assign back states
usdf_18['State'] = state_list

In [209]:
#Getting state abbreviations 
usdf_18 = pd.merge(usdf_18,state_df,on='State')

#dropping unwanted columns
usdf_18.drop(['City Location', 'lat','lng','coordinates','State','Abbrev'], axis=1,inplace=True)

#Renaming Code to State
usdf_18.rename(columns={"Code": "State"},inplace=True)

#Creating a city variable
usdf_18['City'] = usdf_18['Account Name'].str.split(',').str[0]

#dropping account variable
usdf_18.drop(['Account Name'], axis = 1, inplace=True)

In [210]:
#Let's check that we have the state and cities seperately 
usdf_18.head(5)

,Country,Water security risk drivers,Anticipated timescale,Estimated magnitude of potential impact,Risk description,Year,State,City
0,United States of America,Higher water prices,Current,Serious,The water cost burden is felt across all ZIP c...,2018,GA,Atlanta
1,United States of America,Increased water stress or scarcity,Current,Extremely serious,"Lake Mead, which is 90% of Southern Nevada's s...",2018,NV,Las Vegas
2,United States of America,Increased water demand,Current,Serious,Water costs are higher due to infrastructure c...,2018,NV,Las Vegas
3,United States of America,Regulatory,Current,Less Serious,Water restrictions have led to more conservati...,2018,NV,Las Vegas
4,United States of America,Inadequate or ageing infrastructure,Current,Serious,The District's Climate Change Vulnerability As...,2018,DC,Washington

### 2017 US dataset

We repeat the same procedure as in the 2018 dataset for the 2017 dataset to create the state and city columns.

In [211]:
#Creating a coordinate tuple for finding the state using the city location feature

#clean the coorndinates string
usdf_17['City location'] = usdf_17['City location'].str.replace(r'[()]',"")
usdf_17['City location'] = usdf_17['City location'].str.replace('_', '', regex=False)
usdf_17[['lat','lng']]=usdf_17["City location"].str.split(',',expand=True)

#creating the coordinate tuple
usdf_17['coordinates'] = usdf_17[['lat', 'lng']].apply(tuple, axis=1)

/var/folders/nj/bh632zpj6rvfbwpg7f8ff4jr0000gn/T/ipykernel_58660/2043473440.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  usdf_17['City location'] = usdf_17['City location'].str.replace(r'[()]',"")

In [212]:
state_list = [] # Initialize empty list

# get location coordinates
geo_locv  = usdf_17.coordinates.values
for cord in geo_locv:
    # send request
    location = reverse(cord, addressdetails=True)
    # get state value
    state = location.raw["address"].get("state")
    # store state value
    state_list.append(state)
# assign back states
usdf_17['State'] = state_list

In [213]:
#Getting state abbreviations 
usdf_17 = pd.merge(usdf_17,state_df,on='State')

#dropping unwanted columns
usdf_17.drop(['City location', 'lat','lng','coordinates','State','Abbrev'], axis=1, inplace=True)

#Renaming Code to State
usdf_17.rename(columns={"Code": "State"},inplace=True)

#Creating a city variable
usdf_17['City'] = usdf_17['Account Name'].str.split(',').str[0]

#dropping account variable
usdf_17.drop(['Account Name'], axis = 1, inplace=True)

In [214]:
#Let's check that we have the state and cities seperately 
usdf_17.head(5)

,Country,Water security risk drivers,Anticipated timescale,Estimated magnitude of potential impact,Risk description,Year,State,City
0,USA,Increased water stress or scarcity,Current,Extremely serious,NaN,2017,FL,Miami
1,USA,Flooding,Current,Extremely serious,NaN,2017,FL,Miami
2,USA,Increased water stress or scarcity,Current,Serious,Flooding has been one of the main issues that ...,2017,FL,Miami Beach
3,USA,Declining water quality,Current,Less serious,Unknown as this has not been formally assessed...,2017,PA,Abington
4,USA,Flooding,Current,Extremely serious,Severe drought has placed water restrictions o...,2017,PA,Lancaster

## Merging and creating the US dataset

Now that we have our variables of interest, we are ready to merge the three datasets to create on big US dataset!

In [215]:
#Merging all three data frames (2021,2018,2017)
usdf = pd.concat([usdf_21,usdf_18,usdf_17])

In [216]:
#Let's preview the newly created datasets on US cities who responded to the question
usdf.head(5)

,Country,Water security risk drivers,Anticipated timescale,Estimated magnitude of potential impact,Risk description,Year,City,State
1,United States of America,Higher water prices,Current,Serious,The water cost burden is felt across all ZIP c...,2021,City of Atlanta,GA
17,United States of America,Inadequate or ageing water supply infrastructure,Current,Serious,New York City’s drinking water meets orexceeds...,2021,New York City,NY
31,United States of America,Increased water stress,Current,Extremely serious,"Lake Mead, which is 90% of Southern Nevada's s...",2021,City of Las Vegas,NV
35,United States of America,Increased water demand,Current,Serious,Water costs are higher due to infrastructure c...,2021,City of Las Vegas,NV
36,United States of America,Environmental regulations,Current,Less Serious,Water restrictions have led to more conservati...,2021,City of Las Vegas,NV

In [217]:
usdf.tail(5)

,Country,Water security risk drivers,Anticipated timescale,Estimated magnitude of potential impact,Risk description,Year,City,State
48,USA,Increased water stress or scarcity,Current,Less serious,Lack of acceptance for local prioritization in...,2017,Buffalo,NY
49,USA,Increased water stress or scarcity,Current,Extremely serious,"As a desert city, water scarcity is already an...",2017,Tempe,AZ
50,USA,Increased water stress or scarcity,Current,Extremely serious,Our primary source of drinking water comes fro...,2017,Austin,TX
51,USA,Flooding,Current,Serious,Central Texas is a flash flood alley and alway...,2017,Austin,TX
52,USA,Inadequate or aging infrastructure,Current,Serious,The District's Climate Change Vulnerability As...,2017,Washington,DC

Having created our US dataset, we might want to check for missing values and values spelled differently.

In [218]:
#check the values for the waster security risk drivers
usdf["Water security risk drivers"].unique()

array(['Higher water prices',
       'Inadequate or ageing water supply infrastructure',
       'Increased water stress', 'Increased water demand',
       'Environmental regulations', 'Drought', 'Energy supply issues',
       'Severe weather events', 'Declining water quality', nan,
       'Change in land-use', 'Pollution incidents',
       'Increased levels of plastic in freshwater bodies',
       'Ecosystem vulnerability', 'Increased water scarcity',
       'Other, please specify: Radium in water',
       'Other, please specify: Cyber Security',
       'Increased water stress or scarcity', 'Regulatory',
       'Inadequate or ageing infrastructure', 'Flooding',
       'Inadequate or aging infrastructure', 'Water losses'], dtype=object)

In [219]:
#check the values for estimated magnitiude of potential impact
usdf["Estimated magnitude of potential impact"].unique()

array(['Serious', 'Extremely serious', 'Less Serious', nan,
       'Less serious'], dtype=object)

The variable for **waste security risk drivers** and **estimated magnitude of potential** impact have a null element. Additionally **estimate magnitude of potential** impact have two values of *less serious* written differently (i.e., one as "Less Serious" and the other as "Less serious"). Moreover **waste security risk drivers** has "Increased water stress" and "Increased water scarcity" sometimes written as one value "Increased water stress or scarcity", as well as "Inadequate or ageing water supply infrastructure" sometimes written as "Inadequate or ageing infrastructure" or "Inadequate or aging infrastructure". 

Therefore, we will remove rows with null elements and modify the writing of the erroneous values so that they match up.

In [220]:
#remove all the rows with nan 
usdf.dropna(axis = 0, inplace=True)

#replace "Less Serious by "Less serious"
usdf["Estimated magnitude of potential impact"].replace("Less Serious","Less serious", inplace=True)

#replace "Increased water stress" to "Increased water stress or scarcity"
usdf["Water security risk drivers"].replace("Increased water stress","Increased water stress or scarcity", inplace=True)

#replace "Increased water scarcity" to "Increased water stress or scarcity"
usdf["Water security risk drivers"].replace("Increased water scarcity","Increased water stress or scarcity", inplace=True)

#replace "Inadequate or aging infrastructure" to "Inadequate or ageing water supply infrastructure"
usdf["Water security risk drivers"].replace("Inadequate or aging infrastructure","Inadequate or ageing water supply infrastructure", inplace=True)

#replace "Inadequate or ageing infrastructure" to "Inadequate or ageing water supply infrastructure"
usdf["Water security risk drivers"].replace("Inadequate or ageing infrastructure","Inadequate or ageing water supply infrastructure", inplace=True)

In [221]:
#Let's check for the presence of null elements in each column
usdf.isna().sum()

Country                                    0
Water security risk drivers                0
Anticipated timescale                      0
Estimated magnitude of potential impact    0
Risk description                           0
Year                                       0
City                                       0
State                                      0
dtype: int64

In [222]:
#Let's check that the variable waste security risk drivers and estimated magnitude of potential impact no longer have a nan
print("Values of Water security risk drivers: {}.\n".format(usdf["Water security risk drivers"].unique()))
print("Values of Estimated magnitude of potential impact: {}.".format(usdf["Estimated magnitude of potential impact"].unique()))

Values of Water security risk drivers: ['Higher water prices' 'Inadequate or ageing water supply infrastructure'
 'Increased water stress or scarcity' 'Increased water demand'
 'Environmental regulations' 'Drought' 'Energy supply issues'
 'Severe weather events' 'Declining water quality' 'Change in land-use'
 'Pollution incidents' 'Increased levels of plastic in freshwater bodies'
 'Ecosystem vulnerability' 'Other, please specify: Radium in water'
 'Other, please specify: Cyber Security' 'Regulatory' 'Flooding'
 'Water losses'].

Values of Estimated magnitude of potential impact: ['Serious' 'Extremely serious' 'Less serious'].

Great, looks like missing values have been removed and values have been fixed! Let's now drop the **Country** because we do not need it anymore, as well as **Anticipated timescale** because they were all chosen to be "Current".

In [223]:
#drop country
usdf.drop(['Country'], axis=1, inplace=True)

#drop anticipated timescale 
usdf.drop("Anticipated timescale", axis=1, inplace=True)

In [224]:
#let's check what we have so far 
usdf.head(5)

,Water security risk drivers,Estimated magnitude of potential impact,Risk description,Year,City,State
1,Higher water prices,Serious,The water cost burden is felt across all ZIP c...,2021,City of Atlanta,GA
17,Inadequate or ageing water supply infrastructure,Serious,New York City’s drinking water meets orexceeds...,2021,New York City,NY
31,Increased water stress or scarcity,Extremely serious,"Lake Mead, which is 90% of Southern Nevada's s...",2021,City of Las Vegas,NV
35,Increased water demand,Serious,Water costs are higher due to infrastructure c...,2021,City of Las Vegas,NV
36,Environmental regulations,Less serious,Water restrictions have led to more conservati...,2021,City of Las Vegas,NV

Because the cities and states from the 2021 dataset were seperated with a comma and blank space the blank space was added as a leading blank in the variable **state**. Therefore, we will need to delete the leading blank **state**.

In [225]:
#check for leading space in state
usdf['State'].unique()

array([' GA', ' NY', ' NV', ' CA', ' LA', ' UT', ' DC', ' PA', ' OH',
       ' FL', ' IN', ' MO', ' TN', ' HI', ' AL', ' NJ', ' NC', ' MN',
       ' AZ', ' MI', ' CO', ' IA', ' IL', ' NM', ' WI', 'GA', 'NV', 'DC',
       'TN', 'UT', 'OH', 'IN', 'MO', 'HI', 'CA', 'NC', 'WI', 'LA', 'NM',
       'FL', 'PA', 'CO', 'VA', 'NY', 'AZ', 'TX'], dtype=object)

In [226]:
#delete leading blank in State 
usdf["State"] = usdf["State"].str.lstrip()

#check if the leading blank has been deleted
usdf['State'].unique()

array(['GA', 'NY', 'NV', 'CA', 'LA', 'UT', 'DC', 'PA', 'OH', 'FL', 'IN',
       'MO', 'TN', 'HI', 'AL', 'NJ', 'NC', 'MN', 'AZ', 'MI', 'CO', 'IA',
       'IL', 'NM', 'WI', 'VA', 'TX'], dtype=object)

In [227]:
#Let's rearrange the columns to make it easier to read 
usdf = usdf[['Year',
             'State',
             'City',
             'Water security risk drivers',
             'Estimated magnitude of potential impact',
             'Risk description']]
usdf.head(5)

,Year,State,City,Water security risk drivers,Estimated magnitude of potential impact,Risk description
1,2021,GA,City of Atlanta,Higher water prices,Serious,The water cost burden is felt across all ZIP c...
17,2021,NY,New York City,Inadequate or ageing water supply infrastructure,Serious,New York City’s drinking water meets orexceeds...
31,2021,NV,City of Las Vegas,Increased water stress or scarcity,Extremely serious,"Lake Mead, which is 90% of Southern Nevada's s..."
35,2021,NV,City of Las Vegas,Increased water demand,Serious,Water costs are higher due to infrastructure c...
36,2021,NV,City of Las Vegas,Environmental regulations,Less serious,Water restrictions have led to more conservati...

Looks great! We can now export our US dataset into a csv file.

In [229]:
#We will create a csv dataframe of the newly created dataframe to be stored in our file

#export to csv file called "us" 
usdf.to_csv('/Users/jenniferdangguay/Documents/Mirror/School/School/KU/Winter 2022/Modern Data Analytics/Python/Project/Project mda/Draft/us.csv')

Thank you for reading this document! In the next part, we will explore the US dataset (see 2.Data visualisation in the files).